### PR TITLE
signup/signin/signout funcitonality

### PR DESCRIPTION
**Pull request by ctedtsen**
Running npm start should bring you to a homepage, all it says is "Home" at the moment. You can go to localhost:3000/signup to create a new account. Clicking the google symbol will let you sign up using google. You can go to localhost:3000/signin to sign in and you can also sign in using google. Once you sign up or sign in, you will be brought to localhost:3000/account. You should only be able to get to this route if you are signed in. if you are not signed in and try to go to this route, it should bring you to the sign in page. From this page, you can sign out. Once you sign out, you should be redirected to the sign in page.

### CODE REVIEW

**Review by Jasmine211 — COMMENTED** [review]
Looks good to me! Can someone else try to sign up and sign in?

**Comment by endevii** [comment]
So I am getting an error:
"Uncaught Error: FIREBASE FATAL ERROR: Can't determine Firebase Database URL. Be sure to include a Project ID when calling firebase.initializeApp()"
Not exactly sure where the issue is or how to fix it but tried it on both PC and laptop and got the same error.

Edit: I realize now it is in the firbase.js file. It is not working since the process.env file is not included in the code so we have no access to those API keys. At least that is my current understanding of the issue at the moment.

**Comment by ctedtsen** [comment]
I think it might be that I changed it so that it was calling the .env file for the firebase information and I didn't include that in my commit cause its not supposed to be posted to github (prof said that was good practice) but I forgot to send it to you guys separately. I'll send the contents of the .env file on the discord right now.

**Review by endevii — APPROVED** [review]
Really awesome, works great :)

**Pull request merged**
