### PR TITLE
implemented posting reviews on frontend

### PR DESCRIPTION
**Pull request by anicosi1**
Everything works as far as I can tell, but axios error messages are very unspecific. Also needs CSS

### CODE REVIEW

**Review by Jasmine211 — CHANGES_REQUESTED** [review]
Nice, it would be better to add input validation before making a post request. For example, if the user does not put a title or rating, there should be an error message displayed.

**Comment by anicosi1** [comment]
Alright, it displays an error when you're missing inputs now

**Comment by Jasmine211** [comment]
Thanks for the changes. If I don't change the rating value and click submit, it gives me an error because the handleChange function doesn't trigger. So, you can make an option with an empty value: `<select onChange={(e) => handleChange(e)} id="rating" name="rating">
            <option value="">Select Rating</option>` or make a default rating value. This way the user knows to select a rating.

**Review by Jasmine211 — APPROVED** [review]
Thanks for the changes, this looks good to me.

**Pull request merged**
