### PR TITLE
Hopefully fixed remaining tota11y issues + html validation :)

### LINKED ISSUE #73: Fix HTMl Validation
There is some issues with the html validation.

### PR DESCRIPTION
**Pull request by endevii**
I went and did remaining tota11y issues (navbar, buttons, etc.) lmk if there are any issues. closes #73

### CODE REVIEW

**Comment by endevii** [comment]
I'm going to work on html validation now :)

**Comment by endevii** [comment]
Alright, I also fixed validation issues, though the map comes with a ton that I assume are alright since it is caused by it and not us. Feel free to check also because I could have missed a page by accident. I also fixed site images not loading on the site page, the admin page, and the custom itinerary page. #73

**Comment by Jasmine211** [comment]
You caught a lot of the Tota11y errors! One that you did miss is in the /map page, when you click on the pinned location, the site name is a blue that is considered insufficient contrast. Same thing for /itineraries after clicking on generate pdf.

**Comment by endevii** [comment]
Alright, I believe those should be fixed now, great catch! Lmk if I still missed it lol

**Review by Jasmine211 — APPROVED** [review]
Looks good to me!

**Pull request merged**
