### PR TITLE
users can save itineraries

### PR DESCRIPTION
**Pull request by ctedtsen**
I made it so that users can now save itineraries and view their saved itineraries on their account page. To do this, I made it so that a user is created in the mongo database when you register as a new user (meaning you will have to delete your account and reregister so that your user is created in the mongo database). 

On each of the preset itineraries, there should now be a Save Itinerary and Unsave Itinerary button. When the user clicks one, there should be an alert saying the itinerary has been saved or unsaved. If the user clicks the save button and they already have the itinerary saved, there should be an alert telling them that. If they click the unsave button and they don't currently have that itinerary saved, there should also be an alert telling them this. 

For the create your own itinerary, it works exactly the same. However, an itinerary is only considered to have already be saved if it is in the exact same order the user had saved the itinerary as before. for example if the user saves an itinerary as Federal Hall, Fraunces Tavern, then they would not be able to save another itinerary that is Federal Hall, Fraunces Tavern, but they would be able to save an itinerary that is Fraunces Tavern, Federal Hall. This is because of the way I set up the comparison in the data functions but I couldn't get another way to work. I do think this could be ok though since different orders could change the directions and/or timing of the itinerary. 

On the account page, if the user does not have any itineraries, it should say that. Otherwise, it should display the itineraries the user saved and there should be an unsave button at the bottom of each itinerary.

### CODE REVIEW

**Review by Jasmine211 — CHANGES_REQUESTED** [review]
When you render the saved itineraries, make sure to provide a key in the div element (line 76). One suggestion I would make is to just have one button instead of two to save/unsave an itinerary. Nice job overall!

**Comment by ctedtsen** [comment]
Good catch on the warning! I updated the way itineraries are added to the users database so that custom itineraries will be counted as repeats if the user has the same itinerary in a different order saved.. I also made it so that only the save button shows up if the user has not saved the itinerary and only the unsave button shows up if the user has saved the itinerary.

**Comment by ctedtsen** [comment]
I also updated it so only a user who is signed in is able to load more information about the itineraries and create their own itineraries. This stops any errors that would occur if a non signed in user tried to access these parts of the site.

**Review by Jasmine211 — APPROVED** [review]
Thank you for the changes, this looks great!

**Pull request merged**
