### PR TITLE
Add sorting/filter feature

### PR DESCRIPTION
**Pull request by Jasmine211**
Route: /sites

You can now search sites by name and sort them by age, borough, and rating.

### CODE REVIEW

**Comment by endevii** [comment]
One issue that is happening is that when trying to change the sort filter, an error comes up saying "Cannot read properties of null (reading 'reset')". Though I think the issue is in "SiteList.js" line 95 since it can't find an id named "SearchForm" it errors out.

**Comment by endevii** [comment]
Actually, I think I just fixed it, I added the id "searchForm" to the form in "SearchSite.js" and now it works fine. Idk if you want to test that out as well but it works doing it that way. Fantastic job nonetheless!

**Comment by Jasmine211** [comment]
Thanks for catching that!

**Comment by ctedtsen** [comment]
It works great now!

**Review by ctedtsen — APPROVED** [review]

**Pull request merged**
